from book import app, db, Book

books = [
    { "title": "Karma: A Yogi's Guide to Crafting Your Destiny", 
      "price": 11.99, 
      "description": "A new perspective on the overused and misunderstood concept of karma that offers the key to happiness and enlightenment, from the New York Times bestselling author and world-renowned spiritual master Sadhguru. What is karma? Most people understand karma as a balance sheet of good and bad deeds, virtues and sins. The mechanism that decrees that we cannot evade the consequences of our own actions. In reality, karma has nothing to do with reward and punishment. Karma simply means action: your action, your responsibility. It isn't some external system of crime and punishment, but an internal cycle generated by you. Accumulation of karma is determined only by your intention and the way you respond to what is happening to you. Over time, it's possible to become ensnared by your own unconscious patterns of behavior. In Karma, Sadhguru seeks to put you back in the driver's seat, turning you from a terror-struck passenger to a confident driver navigating the course of your own destiny. By living consciously and fully inhabiting each moment, you can free yourself from the cycle. Karma is an exploration and a manual, restoring our understanding of karma to its original potential for freedom and empowerment instead of a source of entanglement. Through Sadhguru's teachings, you will learn how to live intelligently and joyfully in a challenging world.",
      "cover": "karma.jpg",
      "environmental_impact": 3 },
    { "title": "Killing Floor by Lee Child", 
      "price": 9.99,
      "description": "Jack Reacher jumps off a bus and walks fourteen miles down a country road into Margrave, Georgia. An arbitrary decision he's about to regret. Reacher is the only stranger in town on the day they have had their first homicide in thirty years.The cops arrest Reacher and the police chief turns eyewitness to place him at the scene. As nasty secrets leak out, and the body count mounts, one thing is for sure. They picked the wrong guy to take the fall. Although the Jack Reacher novels can be read in any order, Killing Floor is the first book in the internationally popular series. It presents Reacher for the first time, as the tough ex-military cop of no fixed abode: a righter of wrongs, the perfect action hero.",
      "cover": "killing_floor.jpg",
      "environmental_impact": 2 },
    { "title": "A Feast for Crows", 
      "price": 3.99,
      "description": "A Feast for Crows brings to life dark magic, intrigue and terrible bloodshed as the war-torn landscape of the Seven Kingdoms is threatened by destruction as vast as any in its violent past. The War of the Five Kings has ripped Westeros apart. The bloodthirsty, treacherous and cunning Lannisters occupy the Iron Throne, with allies as ruthless as themselves. Lord Frey was host at the Red Wedding, so called for the massacre of the guests, their screams unheard above the music of the feast. Euron Crow’s Eye is as black a pirate as ever raised a sail, sworn to deliver the whole of Westeros to the ironborn. No less to be feared are their enemies. The Starks of Winterfell and the Martells of Dorne seek vengeance for their dead. And the last of the Targaryens, Daenerys Stormborn, will bring fire and blood to King’s Landing when her young dragons reach their terrifying maturity. The last war fought with dragons was a cataclysm powerful enough to shatter the Valyrian peninsula, now a smoking, demon-haunted ruin half drowned by the sea. Against a backdrop of alchemy and murder, victory may go to the men and women possessed of the coldest steel … and the coldest hearts.",
      "cover": "a_feast_for_crows.jpg",
      "environmental_impact": 1 },
    { "title": "The Power of Letting Go",
      "price": 9.99,
      "description": "When you let go, you live intuitively. Everything flows, because you are no longer attached to things being a certain way, to being a certain person or always being right. What a relief. The irony is that when you feel stuck in any area of your life - career, relationships, purpose, health or money - letting go can seem very hard. You cling on for dear life just at the moment you need to take the leap. In The Power of Letting Go, John Purkiss explains why we should let go and how we can do it, using proven techniques to make things happen.",
      "cover": "the_power_of_letting_go.jpg",
      "environmental_impact": 2 },
    { "title": "The Pragmatic Programmer",
      "price": 13.99,
      "description": "The Pragmatic Programmer is one of those rare tech books you'll read, re-read, and read again over the years. Whether you're new to the field or an experienced practitioner, you'll come away with fresh insights each and every time. Dave Thomas and Andy Hunt wrote the first edition of this influential book in 1999 to help their clients create better software and rediscover the joy of coding. These lessons have helped a generation of programmers examine the very essence of software development, independent of any particular language, framework, or methodology, and the Pragmatic philosophy has spawned hundreds of books, screencasts, and audio books, as well as thousands of careers and success stories.",
      "cover": "the_pragmatic_programmer.jpg",
      "environmental_impact": 2 },
    { "title": "Signs: The secret language of the universe",
      "price": 7.99,
      "description": "A modern guide to connecting with the other side, Signs is full of stories of hope. It teaches us how to recognise and interpret the life-changing messages from loved ones and spirit guides, by a renowned psychic medium. aura Lynne Jackson is a psychic medium and the author of the New York Times bestseller The Light Between Us. She possesses an incredible gift: the ability to communicate with loved ones who have passed, convey messages of love and healing, and impart a greater understanding of our interconnectedness. Though her abilities are exceptional, they are not unique, and that is the message at the core of this book. Understanding 'the secret language of the universe' is a gift available to all. As we learn to ask for and recognise signs from the other side, we will start to find meaning where before there was only confusion, and see light in the darkness. We may decide to change paths, push toward love, pursue joy, and engage with life in a whole new way.",
      "cover": "signs.jpg",
      "environmental_impact": 1 }
]

with app.app_context():
    db.create_all() # creates the empty tables
    
    for book in books:
        newBook = Book(title=book["title"], price=book["price"], description=book["description"], cover=book["cover"], environmental_impact=book["environmental_impact"])
        db.session.add(newBook)
    
    db.session.commit()